// <auto-generated />
using System;
using GuideApp.WebApp.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuideApp.WebApp.Migrations
{
    [DbContext(typeof(CompanyInfoContext))]
    [Migration("20241109131600_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");

            modelBuilder.Entity("GuideApp.WebApp.Models.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88f6b39b-0661-4ed7-8532-7b968958fa20"),
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("a833d2d5-0f38-4601-83ca-b86a7501f461"),
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = new Guid("e6a2dec0-071c-4350-a150-ca80cd1d369e"),
                            Name = "Google"
                        },
                        new
                        {
                            Id = new Guid("c2a41658-3fcc-4694-b0c2-3b156aff4c9c"),
                            Name = "Yandex"
                        },
                        new
                        {
                            Id = new Guid("fe4636e2-ef3d-4368-9dbd-026d6298dfda"),
                            Name = "VK"
                        });
                });

            modelBuilder.Entity("GuideApp.WebApp.Models.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f47e2d1-1b57-4cb4-ae88-0a1b3f24f876"),
                            CompanyId = new Guid("88f6b39b-0661-4ed7-8532-7b968958fa20"),
                            Name = "Департамент инноваций"
                        },
                        new
                        {
                            Id = new Guid("9a56e540-f8ea-47b1-8824-1d0f6e57429e"),
                            CompanyId = new Guid("88f6b39b-0661-4ed7-8532-7b968958fa20"),
                            Name = "Департамент дизайна"
                        },
                        new
                        {
                            Id = new Guid("c1bfe5f3-0e35-4b7e-98a0-88b2e1b02c33"),
                            CompanyId = new Guid("88f6b39b-0661-4ed7-8532-7b968958fa20"),
                            Name = "Департамент маркетинга"
                        },
                        new
                        {
                            Id = new Guid("b7a21d20-55cf-49f6-bf3e-02f5a7ef5653"),
                            CompanyId = new Guid("a833d2d5-0f38-4601-83ca-b86a7501f461"),
                            Name = "Департамент программного обеспечения"
                        },
                        new
                        {
                            Id = new Guid("31b8c9f2-9f52-4e32-b9ae-bcb02e8a91b2"),
                            CompanyId = new Guid("a833d2d5-0f38-4601-83ca-b86a7501f461"),
                            Name = "Департамент искусственного интеллекта"
                        },
                        new
                        {
                            Id = new Guid("ad47bfb1-8baf-4e41-b9c4-407e6b34c159"),
                            CompanyId = new Guid("a833d2d5-0f38-4601-83ca-b86a7501f461"),
                            Name = "Департамент поддержки пользователей"
                        },
                        new
                        {
                            Id = new Guid("7f4fbd5b-80c2-42fc-89a0-94a0b4e7c37a"),
                            CompanyId = new Guid("e6a2dec0-071c-4350-a150-ca80cd1d369e"),
                            Name = "Департамент поисковых технологий"
                        },
                        new
                        {
                            Id = new Guid("e9b8d1ab-c53c-49be-8e5c-b19f6d58a144"),
                            CompanyId = new Guid("e6a2dec0-071c-4350-a150-ca80cd1d369e"),
                            Name = "Департамент облачных сервисов"
                        },
                        new
                        {
                            Id = new Guid("c68aeb41-d4ff-49b2-b68a-74ab123bfb3c"),
                            CompanyId = new Guid("e6a2dec0-071c-4350-a150-ca80cd1d369e"),
                            Name = "Департамент рекламы и аналитики"
                        },
                        new
                        {
                            Id = new Guid("20b1edc4-34c4-4052-b4f3-143e558ed1c5"),
                            CompanyId = new Guid("c2a41658-3fcc-4694-b0c2-3b156aff4c9c"),
                            Name = "Департамент онлайн-сервисов"
                        },
                        new
                        {
                            Id = new Guid("b80c1ed8-c0b7-45a4-bb93-98b0a6b0e142"),
                            CompanyId = new Guid("c2a41658-3fcc-4694-b0c2-3b156aff4c9c"),
                            Name = "Департамент поиска и аналитики"
                        },
                        new
                        {
                            Id = new Guid("d7c917c9-4762-4ad1-a6e1-3d6b604d733e"),
                            CompanyId = new Guid("c2a41658-3fcc-4694-b0c2-3b156aff4c9c"),
                            Name = "Департамент медиасервисов"
                        },
                        new
                        {
                            Id = new Guid("d25109a6-8f34-4f18-b13e-5f9bdf732374"),
                            CompanyId = new Guid("fe4636e2-ef3d-4368-9dbd-026d6298dfda"),
                            Name = "Департамент социальных сетей"
                        },
                        new
                        {
                            Id = new Guid("a384db73-2fd4-4657-9b25-74a1fd0fe31d"),
                            CompanyId = new Guid("fe4636e2-ef3d-4368-9dbd-026d6298dfda"),
                            Name = "Департамент контента и медиаплатформ"
                        },
                        new
                        {
                            Id = new Guid("b6a8fa34-9821-4d38-bdea-c03f4e90f7ad"),
                            CompanyId = new Guid("fe4636e2-ef3d-4368-9dbd-026d6298dfda"),
                            Name = "Департамент безопасности"
                        });
                });

            modelBuilder.Entity("GuideApp.WebApp.Models.Entities.Office", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b8de14e-75e9-4dc3-b4b3-30272ab7cd6f"),
                            DepartmentId = new Guid("0f47e2d1-1b57-4cb4-ae88-0a1b3f24f876"),
                            Name = "Отдел исследований и разработок продуктов"
                        },
                        new
                        {
                            Id = new Guid("7e4e6f3f-1d34-4814-9b45-d5a0c814e716"),
                            DepartmentId = new Guid("0f47e2d1-1b57-4cb4-ae88-0a1b3f24f876"),
                            Name = "Отдел анализа потребительских трендов"
                        },
                        new
                        {
                            Id = new Guid("d29d56c8-2834-44b7-b94a-9b73cf4b8b10"),
                            DepartmentId = new Guid("9a56e540-f8ea-47b1-8824-1d0f6e57429e"),
                            Name = "Отдел UX/UI дизайна"
                        },
                        new
                        {
                            Id = new Guid("1ab227bb-3d3c-4e54-8463-580bd6cb2d42"),
                            DepartmentId = new Guid("9a56e540-f8ea-47b1-8824-1d0f6e57429e"),
                            Name = "Отдел промышленного дизайна"
                        },
                        new
                        {
                            Id = new Guid("4d18e3ec-6bfa-485d-b8d5-9fba83dc7e75"),
                            DepartmentId = new Guid("c1bfe5f3-0e35-4b7e-98a0-88b2e1b02c33"),
                            Name = "Отдел цифрового маркетинга"
                        },
                        new
                        {
                            Id = new Guid("0d8e2fb1-5804-4de6-860b-38e9e1b126fd"),
                            DepartmentId = new Guid("c1bfe5f3-0e35-4b7e-98a0-88b2e1b02c33"),
                            Name = "Отдел креативных кампаний"
                        },
                        new
                        {
                            Id = new Guid("41b6a5a3-2797-4828-bf07-2d0c7a6e340b"),
                            DepartmentId = new Guid("b7a21d20-55cf-49f6-bf3e-02f5a7ef5653"),
                            Name = "Отдел разработки операционных систем"
                        },
                        new
                        {
                            Id = new Guid("3bfa5c79-44da-4637-8db8-3127e8b72c24"),
                            DepartmentId = new Guid("b7a21d20-55cf-49f6-bf3e-02f5a7ef5653"),
                            Name = "Отдел разработки облачных решений"
                        },
                        new
                        {
                            Id = new Guid("d96d0d3d-feca-4d49-93d4-5a0c4f073570"),
                            DepartmentId = new Guid("31b8c9f2-9f52-4e32-b9ae-bcb02e8a91b2"),
                            Name = "Отдел обработки естественного языка"
                        },
                        new
                        {
                            Id = new Guid("6b42db18-cb59-45c6-a144-e1a12d306cb1"),
                            DepartmentId = new Guid("31b8c9f2-9f52-4e32-b9ae-bcb02e8a91b2"),
                            Name = "Отдел машинного обучения"
                        },
                        new
                        {
                            Id = new Guid("0e8f5799-58bc-4df5-9878-3b6e7f6c857f"),
                            DepartmentId = new Guid("ad47bfb1-8baf-4e41-b9c4-407e6b34c159"),
                            Name = "Отдел технической поддержки"
                        },
                        new
                        {
                            Id = new Guid("bb137dd8-7b15-4a3b-a715-d8ed7ed2a2eb"),
                            DepartmentId = new Guid("ad47bfb1-8baf-4e41-b9c4-407e6b34c159"),
                            Name = "Отдел управления контентом знаний"
                        },
                        new
                        {
                            Id = new Guid("f1b0192e-2c02-49c6-9552-8b0bfc8e41f0"),
                            DepartmentId = new Guid("7f4fbd5b-80c2-42fc-89a0-94a0b4e7c37a"),
                            Name = "Отдел алгоритмов ранжирования"
                        },
                        new
                        {
                            Id = new Guid("7cfa34f4-2c37-492f-bb91-e267d7e5589f"),
                            DepartmentId = new Guid("7f4fbd5b-80c2-42fc-89a0-94a0b4e7c37a"),
                            Name = "Отдел пользовательских интерфейсов поиска"
                        },
                        new
                        {
                            Id = new Guid("5b39067a-235b-46e2-b68e-facb66b0f70b"),
                            DepartmentId = new Guid("e9b8d1ab-c53c-49be-8e5c-b19f6d58a144"),
                            Name = "Отдел инфраструктуры хранения данных"
                        },
                        new
                        {
                            Id = new Guid("91fc03a4-5667-49f4-aaa5-e4a39929f39f"),
                            DepartmentId = new Guid("e9b8d1ab-c53c-49be-8e5c-b19f6d58a144"),
                            Name = "Отдел управления вычислительными мощностями"
                        },
                        new
                        {
                            Id = new Guid("09c78b26-5074-4935-b32f-f86f09e4c563"),
                            DepartmentId = new Guid("c68aeb41-d4ff-49b2-b68a-74ab123bfb3c"),
                            Name = "Отдел разработки рекламных инструментов"
                        },
                        new
                        {
                            Id = new Guid("2f631f73-8903-47b2-85a1-5187b25a5299"),
                            DepartmentId = new Guid("c68aeb41-d4ff-49b2-b68a-74ab123bfb3c"),
                            Name = "Отдел анализа данных"
                        },
                        new
                        {
                            Id = new Guid("8d7c591d-80d1-4635-a807-120b2fe5ec49"),
                            DepartmentId = new Guid("20b1edc4-34c4-4052-b4f3-143e558ed1c5"),
                            Name = "Отдел развития сервисов доставки"
                        },
                        new
                        {
                            Id = new Guid("0aa1c4d4-3481-42be-9f24-f050ef7b751b"),
                            DepartmentId = new Guid("20b1edc4-34c4-4052-b4f3-143e558ed1c5"),
                            Name = "Отдел разработки картографических решений"
                        },
                        new
                        {
                            Id = new Guid("319b7a4f-652d-4f32-b934-b5127fa563a5"),
                            DepartmentId = new Guid("b80c1ed8-c0b7-45a4-bb93-98b0a6b0e142"),
                            Name = "Отдел алгоритмов поиска"
                        },
                        new
                        {
                            Id = new Guid("e8d3a1c2-c5c7-4d72-8af4-f6ad6c8a6fdd"),
                            DepartmentId = new Guid("b80c1ed8-c0b7-45a4-bb93-98b0a6b0e142"),
                            Name = "Отдел аналитики больших данных"
                        },
                        new
                        {
                            Id = new Guid("3c506b5f-3157-4aef-bf99-83b2dd4dfce4"),
                            DepartmentId = new Guid("d7c917c9-4762-4ad1-a6e1-3d6b604d733e"),
                            Name = "Отдел музыкальных сервисов"
                        },
                        new
                        {
                            Id = new Guid("e2e51f75-c65c-4c0a-8b48-f6c1847c57b6"),
                            DepartmentId = new Guid("d7c917c9-4762-4ad1-a6e1-3d6b604d733e"),
                            Name = "Отдел видеосервисов"
                        },
                        new
                        {
                            Id = new Guid("7ad631b8-9783-4c19-a7db-e5fd38476fd4"),
                            DepartmentId = new Guid("d25109a6-8f34-4f18-b13e-5f9bdf732374"),
                            Name = "Отдел разработки мобильных приложений"
                        },
                        new
                        {
                            Id = new Guid("1d0c7c33-7b7e-4525-9908-7e991fb26a6a"),
                            DepartmentId = new Guid("d25109a6-8f34-4f18-b13e-5f9bdf732374"),
                            Name = "Отдел веб-разработки"
                        },
                        new
                        {
                            Id = new Guid("ff1d9e75-3c67-4d21-b782-e9351ff5ab6c"),
                            DepartmentId = new Guid("a384db73-2fd4-4657-9b25-74a1fd0fe31d"),
                            Name = "Отдел создания и курирования видеоконтента"
                        },
                        new
                        {
                            Id = new Guid("d51f6231-9583-4d2e-bf20-b65fca03713d"),
                            DepartmentId = new Guid("a384db73-2fd4-4657-9b25-74a1fd0fe31d"),
                            Name = "Отдел поддержки музыкальных проектов"
                        },
                        new
                        {
                            Id = new Guid("9b420fea-c3e3-4d7a-9a9f-79abbeccf94f"),
                            DepartmentId = new Guid("b6a8fa34-9821-4d38-bdea-c03f4e90f7ad"),
                            Name = "Отдел защиты данных пользователей"
                        },
                        new
                        {
                            Id = new Guid("572a3128-76c2-4b9a-93db-b6b31e22c7f5"),
                            DepartmentId = new Guid("b6a8fa34-9821-4d38-bdea-c03f4e90f7ad"),
                            Name = "Отдел мониторинга и реагирования на инциденты"
                        });
                });

            modelBuilder.Entity("GuideApp.WebApp.Models.Entities.Department", b =>
                {
                    b.HasOne("GuideApp.WebApp.Models.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("GuideApp.WebApp.Models.Entities.Office", b =>
                {
                    b.HasOne("GuideApp.WebApp.Models.Entities.Department", "Department")
                        .WithMany("Offices")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GuideApp.WebApp.Models.Entities.Company", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("GuideApp.WebApp.Models.Entities.Department", b =>
                {
                    b.Navigation("Offices");
                });
#pragma warning restore 612, 618
        }
    }
}
